### ISSUE TITLE
Request to build version >= 1.24.3 for osx

### ISSUE THREAD

**Issue by farleylai** [conda-forge/grpcio-feedstock#18]
`tensorboard`-2.1.1 requires `grpcio` >=1.24.3 but there is only version 1.23 is available for osx.
The version in the default channel stays in 1.16, way behind windows and linux too.
I tried building 1.28.1 with the current recipe by changing the version number and sha256 without any noticeable issue.
Is there any reason for the discrepancy?

**Comment by jschueller** [comment]
fixed in #19
