### ISSUE TITLE
conda forge grpcio version can not keep up with official version

### ISSUE THREAD

**Issue by kevinwang930** [conda-forge/grpcio-feedstock#50]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
I use conda for a long period of time, it works fine. but one thing I can not understand is that for some packages the the conda-forge version can not keep up with the official release. the current official release version of grpcio is v1.41, but conda-forge version is v1.38, 3 minor release behind. can anyone kindly explain to me why ? 
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by bollwyvl** [comment]
Speaking for myself: `grpcio` is somewhat tricky to get building everywhere, and doesn't provide a _lot_ of value to me in and of itself. My effort on updating it is primarily driven by when a downstream i _do_ care about needs to update... which is usually rare, once we get a downstream to accept that one of the benefits of grpc is that it _is_ backwards-compatible, and _doesn't_ need to be on the bleeding edge.

If you're interested in helping keep the package up-to-date, feel free to submit a PR and and yourself to the `feedstock-maintainers` key in `extras`, and we can get you added! I had started one earlier, and it got closed, but there's likely a few fixes that can be cross-applied.

**Comment by kevinwang930** [comment]
@bollwyvl  thanks for your explanation and especially for your works. I am a newcomer in the programming field, your explanation let me know the reason conda package version is behind the official release. For now I don't think I can work out a PR, I still have a lot to learn, thank you !
