### ISSUE TITLE
No Windows Python 2.7 build

### ISSUE THREAD

**Issue by tswast** [conda-forge/grpcio-feedstock#6]
I noticed in https://github.com/conda-forge/google-cloud-bigquery-storage-feedstock/pull/2 that there isn't a Windows build for Python 2.7.

Do you exclude it from the builds at all, or does it just happen to fail on Windows Python 2.7? If you are excluding it, I'd love to know how so that I can do the same on https://github.com/conda-forge/google-cloud-bigquery-storage-feedstock.

**Comment by ocefpaf** [comment]
There is a comment there about `protobuf` I but I recall what that means and it doesn't really explain the link between `grpcio` and `protobuf`. If you want to try it on win+py27 please send a PR.

**Comment by tswast** [comment]
I think the core problem is here: https://github.com/conda-forge/protobuf-feedstock/commit/791e5ce330dad4ab2ce16e9d549e7b1cc2c46d80 Apparently protobuf is using C++ 11 features.

**Comment by ocefpaf** [comment]
Conda-forge is no longer supporting Python 2.7. Closing this.
